hlxsites/famous-smoke-cigaradvisor

- README.md
Fix #<gh-issue-id>
Test URLs:
- After: https://update-readme-coordinates--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/
> Update readme coordinates

- cigaradvisor/blocks/article-teaser/article-teaser.css
Fix https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/39
Test URLs:
- After: https://feature-gridlayout--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/drafts/Kailas/new-grid
> fixing the gap

- README.md
Fix #<gh-issue-id>
Test URLs:
- After: https://issue-33-1--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/
> issue-33 - link to import code branch

- cigaradvisor/blocks/contest-form/contest-form.css
- cigaradvisor/blocks/contest-form/contest-form.js
Issue: https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/12
Test URL:
https://feature-contest-form--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/drafts/Kailas/contest-form
> Contest Form

- helix-query.yaml
Part of #23 
Test URLs:
- After: https://issue-23--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/
> Add author index

- cigaradvisor/styles/styles.css
Test URLs:
- After: https://bugfix-section-header--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/
> Homepage stylized-header

- cigaradvisor/blocks/article-list/article-list.js
Issue: https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/10
Test URLs:
- After: https://feature-curated-artlist--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/must-reads
> Curated article-list

- cigaradvisor/blocks/article-teaser/article-teaser.js
- cigaradvisor/scripts/scripts.js
Test URLs:
- After: https://feat-article-teaser--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/
> Auto-Select next Article in Teasers

- cigaradvisor/blocks/article-list/article-list.css
- cigaradvisor/blocks/article-list/article-list.js
- cigaradvisor/blocks/author-list/author-list.css
- cigaradvisor/blocks/author-list/author-list.js
- cigaradvisor/blocks/author-teaser/author-teaser.css
- cigaradvisor/blocks/author-teaser/author-teaser.js
- cigaradvisor/scripts/scripts.js
- cigaradvisor/scripts/util.js
Fix #130 
Test URLs:
- After: https://feat-more-article-list--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/author
- After: https://feat-more-article-list--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/category/buying-guides
- After: https://feat-more-article-list--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/fragments/404
> Article List Improvements

- cigaradvisor/scripts/scripts.js
- cigaradvisor/styles/styles.css
Test URLs:
- https://bug-image-cls--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/cigar-contest
> Fix CLS for images in initial viewport

- cigaradvisor/styles/styles.css
issue: https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/134
Test URLs:
- Before: https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/cigar-contest
- After: https://bug-contest-styling--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/cigar-contest
> center align

- cigaradvisor/blocks/header/header.css
- cigaradvisor/blocks/header/header.js
- cigaradvisor/blocks/hero/hero.css
- cigaradvisor/blocks/hero/hero.js
Fix : https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/138
Test URLs:
- After: https://feature-search--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> search form styling

- cigaradvisor/sitemap_index.xml
- helix-sitemap.yaml
> Add Sitemap.

- cigaradvisor/blocks/footer/footer.css
- cigaradvisor/styles/styles.css
Test URLs:
- After: https://bug-footer-styling--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> Fix footer styling

- cigaradvisor/scripts/templates/blog-post.js
Test URLs:
- After: https://bug-article-nav--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/articles/2024/1/my-weekend-cigar-review-alec-bradley-black-market-esteli
> Add autoblock nav to article pages

- cigaradvisor/blocks/article-list/article-list.js
Test URLs:
- After: https://bug-article-list-limit--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/category/buying-guides
> Article List isn't honoring limt

- cigaradvisor/blocks/footer/footer.css
Fix #173 
Test URLs:
- After: https://bug-footer--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> Fix fooder wrap.

- cigaradvisor/blocks/return-to-top/return-to-top.css
- cigaradvisor/blocks/return-to-top/return-to-top.js
Test URLs:
- After: https://bug-rtt-breakpoint--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> Use standard breakpoints for the RTT feature

- cigaradvisor/blocks/article-navigation/article-navigation.css
- cigaradvisor/blocks/article-teaser/article-teaser.css
- cigaradvisor/blocks/articleheader/articleheader.css
- cigaradvisor/blocks/author-detail/author-detail.css
- cigaradvisor/blocks/author-teaser/author-teaser.css
- cigaradvisor/blocks/captioned-image/captioned-image.css
- cigaradvisor/blocks/footer/footer.css
- cigaradvisor/blocks/header/header.css
- cigaradvisor/styles/styles.css
- cigaradvisor/styles/templates/blog-post.css
Test URLs:
- After: https://bug-post-styles--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/articles/2024/1/cigar-advisor-guide-cle-cigars
> Fix some styling and use variables for stuff.

- cigaradvisor/blocks/author-card/author-card.js
- cigaradvisor/blocks/carousel/carousel.js
- cigaradvisor/blocks/footer/footer.js
- cigaradvisor/blocks/imagecta/imagecta.js
- cigaradvisor/scripts/scripts.js
Test URLs:
- After: https://bug-external-links--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> addig /cigaradvisor path check

- cigaradvisor/blocks/carousel/carousel.js
Fix https://github.com/hlxsites/famous-smoke-cigaradvisor/issues/181
Test URLs:
- After: https://bug-carousel-autoscroll--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> Fix autoscroll for >1 carousels on page

- cigaradvisor/blocks/header/header.css
Fix #180 
Test URLs:
- After: https://bug-more-header--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> More header fixees.

- cigaradvisor/blocks/article-teaser/article-teaser.js
- cigaradvisor/blocks/articleheader/articleheader.js
- cigaradvisor/blocks/author-card/author-card.js
- cigaradvisor/blocks/author-teaser/author-teaser.js
- cigaradvisor/blocks/hero/hero.js
- cigaradvisor/scripts/scripts.js
Fix #193 
Test URLs:
- After: https://feat-image-urls--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
- After: https://feat-image-urls--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/must-reads
- After: https://feat-image-urls--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/category/cigar-reviews/my-weekend-cigar-review-red-meat-lovers-filet-mignon
> Make image URLs user/seo friendly.

- cigaradvisor/blocks/promotion-banner/promotion-banner.css
- cigaradvisor/blocks/promotion-banner/promotion-banner.js
Fix #183
Test URLs:
- After: https://issue-183--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> Add promotion banner block

- helix-sitemap.yaml
Test URLs:
- After: https://bug-sitemap-index--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> Fix Sitemap Typos

- cigaradvisor/blocks/article-list/article-list.js
- cigaradvisor/scripts/linking-data.js
- cigaradvisor/scripts/templates/blog-post.js
- cigaradvisor/scripts/util.js
Fix #230
Test URLs:
- After: https://issue-230--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> issue-230 - adjust to `category`-less path structure

- helix-query.yaml
Fix #238
Test URLs:
- After: https://starts-star-not-a-string--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> Add quotes to excludes string properties

- cigaradvisor/scripts/templates/blog-post.js
- helix-sitemap.yaml
Fix #250
Test URLs:
- Before: https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/buying-guides/new-cigars-march-4-2024
- After: https://issue-250--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/buying-guides/new-cigars-march-4-2024
> issue-250 - always select 4 posts

- cigaradvisor/blocks/footer/footer.css
- cigaradvisor/blocks/footer/footer.js
Fix #268
Test URLs:
- After: https://issue-268--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> issue-268 - add Truevault California Privacy Notice

- cigaradvisor/blocks/article-list/article-list.js
Fix #260
Test URLs:
- Before: https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/must-reads
- After: https://issue-260--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/must-reads
> issue-260 - reduce TBT

- cigaradvisor/blocks/article-list/article-list.js
- cigaradvisor/scripts/scripts.js
Fix #261
Test URLs:
- Before: https://main--famous-smoke-cigaradvisor--hlxsites.hlx.live/cigaradvisor/moreposts
- After: https://issue-261-high-lcp--famous-smoke-cigaradvisor--hlxsites.hlx.live/cigaradvisor/moreposts
> issue-261 - reduce TBT

- cigaradvisor/blocks/articleheader/articleheader.css
- cigaradvisor/blocks/articleheader/articleheader.js
Fix #281
Test URLs:
- After: https://bug-281--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> Remove publish date from article header

- cigaradvisor/blocks/article-navigation/article-navigation.css
Fix #284 
Test URLs:
- After: https://bug-284--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> Fix article navigation padding

- cigaradvisor/blocks/return-to-top/return-to-top.js
- cigaradvisor/scripts/util.js
Fix #293
Test URLs:
- Before: https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/buying-guides
- After: https://issue-293--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/buying-guides
> issue-293 - scroll to top when navigating more posts

- cigaradvisor/scripts/scripts.js
Test URLs:
- After: https://bug-homepage-images--famous-smoke-cigaradvisor--hlxsites.hlx.live/cigaradvisor
> Fix images.

- tools/sidekick/config.json
Fix #290 
Test URLs:
- Before: https://main--famous-smoke-cigaradvisor--hlxsites.hlx.live/cigaradvisor
- After: https://issue-290--famous-smoke-cigaradvisor--hlxsites.hlx.live/cigaradvisor
> issue-290 - Update sidekick configuration host

- cigaradvisor/docs/create-category.md
- cigaradvisor/scripts/util.js
- cigaradvisor/sitemap_index.xml
- fstab.yaml
- helix-query.yaml
- helix-sitemap.yaml
Test URLs:
- After: https://feat-remove-uncategorized--famous-smoke-cigaradvisor--hlxsites.hlx.live/cigaradvisor
> Remove Uncategorized category

- helix-sitemap.yaml
Test URLs:
- After: https://bug-sitemap-dates--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> Remove dates from sitemaps.

- cigaradvisor/styles/styles.css
Fix #299
Test URLs:
- After: https://scrollbar-gutter--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
> prevents layout changes

- cigaradvisor/blocks/table/table.css
- cigaradvisor/blocks/table/table.js
Fix #316
Test URLs:
- Before: https://main--famous-smoke-cigaradvisor--hlxsites.aem.page/cigaradvisor/buying-guides/cohiba-cigars
- After: https://316-add-table-block--famous-smoke-cigaradvisor--hlxsites.aem.page/cigaradvisor/buying-guides/cohiba-cigars
> 316 add table block
